name: Bitesizedhealthyhabits
favicon: null
layout_spectrum: 0.8899800241924822
typography_spectrum: 0.17469445802271366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7724364071618766
  lightness: 0.9685260790865868
  saturation: 0.648262731032446
  rhythmicContrast: 0.2931955214589834
purpose: []
